<a href="https://colab.research.google.com/github/phoebelh/PyTorch/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
myTorch = torch.arange(10)
myTorch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# reshape and view
myTorch = myTorch.reshape(2,5)
myTorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
# we can also reshape if we dont know the number of items using -1
myTorch2 = torch.arange(10)
myTorch2 = myTorch2.reshape(-1,2)
myTorch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [8]:
myTorch3 = torch.arange(10)
myTorch3 = myTorch3.view(2,5)
myTorch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# with reshape and view, they will pdate
myTorch5 = torch.arange(10)
myTorch5 = myTorch5.reshape(2,5)
myTorch5[0,0] = 10
myTorch5
# all by reference

tensor([[10,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [12]:
# grabs a specific item
myTorch6 = torch.arange(10)
myTorch6[7]


tensor(7)

In [16]:
# grab a slice
myTorch[:,1]

tensor([1, 6])

# **TENSOR MATH OPERATIONS**


*   Add, subtract, multiply, divide, exponents, remainders
*   Shorthand and longhand
*  Reassignment



In [17]:
import numpy as np

In [18]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [19]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [20]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [22]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [23]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [25]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [26]:
# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [27]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [28]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [30]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [29]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [31]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [32]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [33]:
# reassignment
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [34]:
tensor_a

tensor([ 6,  8, 10, 12])