<a href="https://colab.research.google.com/github/phoebelh/PyTorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**TENSORS**
- A `torch`. Tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar to Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).
- Default data type of `float32`.
- More suitable for deep learning than a numpy array.

In [ ]:
import torch
import numpy as np

# **LISTS**

In [5]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

# **NUMPY ARRAYS**

In [7]:
np1 = np.random.rand(3)
np1

array([0.29205862, 0.81402922, 0.83940367])

# **TENSORS**

In [12]:
tensor_2d = torch.randn(3)
tensor_3d = torch.zeros(3,3,3)
tensor_2d,tensor_3d

(tensor([1.0159, 0.2707, 0.6465]),
 tensor([[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],
 
         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]))

In [13]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([0.2921, 0.8140, 0.8394], dtype=torch.float64)